# Generated by Django 3.1.2 on 2020-10-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='userImage',
            field=models.ImageField(upload_to='Profiles'),
        ),
        migrations.AlterField(
            model_name='coursepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='CoursePost'),
        ),
    ]
