# Generated by Django 3.1.1 on 2020-10-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201013_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='enrolls',
            field=models.IntegerField(default=0),
        ),
    ]
