# Generated by Django 3.1.1 on 2020-10-16 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_enroll_enrolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='user',
        ),
        migrations.AddField(
            model_name='enroll',
            name='enrolluser',
            field=models.ManyToManyField(related_name='enrollinguser', to=settings.AUTH_USER_MODEL),
        ),
    ]
