# Generated by Django 3.1.1 on 2020-10-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201016_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='enrolluser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='enrolls',
        ),
    ]
