# Generated by Django 3.1.2 on 2020-10-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pict',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='Message'),
        ),
    ]
