# Generated by Django 3.1.2 on 2020-10-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20201011_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pict',
            field=models.ImageField(blank=True, null=True, upload_to='Message'),
        ),
    ]
